# https://dev.to/brunorobert/github-and-gitlab-sync-44mn
# This pushes code from GitHub to Gitlab upon commit to GH
name: Gitlab Sync

on:
  push:
    branches:
    - main
  #delete: {}

permissions: read-all

jobs:
  sync:
    runs-on: ubuntu-24.04
    name: Git Repo Sync
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
      with:
        egress-policy: block
        disable-telemetry: true
        allowed-endpoints: 
          github.com:443
          gitlab.com:443
        
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0
        
    - uses: jauderho/git-repo-sync@6142c9cd8960dadc57d1190506d6c35ac5cee660 # v0.3.0
      with:
        # Such as https://github.com/wangchucheng/git-repo-sync.git
        #target-url: ${{ secrets.GITLAB_URL }}
        target-url: https://gitlab.com/${{ github.repository }}.git
        # Such as wangchucheng
        #target-username: ${{ secrets.GITLAB_USERNAME }}
        target-username: ${{ github.actor }}
        # You can store token in your project's 'Setting > Secrets' and reference the name here. Such as ${{ secrets.ACCESS\_TOKEN }}
        target-token: ${{ secrets.GITLAB_TOKEN }}
