# https://dev.to/brunorobert/github-and-gitlab-sync-44mn
# This pushes code from GitHub to Gitlab upon commit to GH
name: Gitlab Sync

on:
  push:
    branches:
    - main
  #delete: {}

permissions: read-all

jobs:
  sync:
    runs-on: ubuntu-22.04
    name: Git Repo Sync
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@248ae51c2e8cc9622ecf50685c8bf7150c6e8813 # v1
      with:
        egress-policy: block
        disable-telemetry: true
        allowed-endpoints: 
          github.com:443
          gitlab.com:443
        
    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v2
      with:
        fetch-depth: 0
        
    - uses: jauderho/git-repo-sync@6142c9cd8960dadc57d1190506d6c35ac5cee660 # v0.1.0
      with:
        # Such as https://github.com/wangchucheng/git-repo-sync.git
        #target-url: ${{ secrets.GITLAB_URL }}
        target-url: https://gitlab.com/${{ github.repository }}.git
        # Such as wangchucheng
        #target-username: ${{ secrets.GITLAB_USERNAME }}
        target-username: ${{ github.actor }}
        # You can store token in your project's 'Setting > Secrets' and reference the name here. Such as ${{ secrets.ACCESS\_TOKEN }}
        target-token: ${{ secrets.GITLAB_TOKEN }}
